export interface I_product {
  manufacturer: string;
  vehicle: string;
  model: string;
  type: string;
  fuel: string;
  color: string;
}

export const productDetails:I_product[] = [
  {
    manufacturer: "BMW",
    vehicle: "BMW 1",
    model: "Model 3",
    type: "SUV",
    fuel: "Gasoline",
    color: "indigo",
  },
  {
    manufacturer: "Polestar",
    vehicle: "Aston Martin El Camino",
    model: "XC90",
    type: "Hatchback",
    fuel: "Gasoline",
    color: "magenta",
  },
  {
    manufacturer: "Bugatti",
    vehicle: "Mini 1",
    model: "Cruze",
    type: "Minivan",
    fuel: "Gasoline",
    color: "silver",
  },
  {
    manufacturer: "Rolls Royce",
    vehicle: "Hyundai Beetle",
    model: "XTS",
    type: "Hatchback",
    fuel: "Diesel",
    color: "black",
  },
  {
    manufacturer: "Toyota",
    vehicle: "Honda 911",
    model: "Wrangler",
    type: "Sedan",
    fuel: "Hybrid",
    color: "tan",
  },
  {
    manufacturer: "Fiat",
    vehicle: "Chevrolet Prius",
    model: "CX-9",
    type: "SUV",
    fuel: "Diesel",
    color: "olive",
  },
  {
    manufacturer: "Maserati",
    vehicle: "Ford Beetle",
    model: "CX-9",
    type: "Minivan",
    fuel: "Hybrid",
    color: "red",
  },
  {
    manufacturer: "Chevrolet",
    vehicle: "Maserati Wrangler",
    model: "Grand Cherokee",
    type: "Crew Cab Pickup",
    fuel: "Hybrid",
    color: "teal",
  },
  {
    manufacturer: "BMW",
    vehicle: "Rolls Royce Challenger",
    model: "Land Cruiser",
    type: "Sedan",
    fuel: "Hybrid",
    color: "turquoise",
  },
  {
    manufacturer: "Volvo",
    vehicle: "Porsche Model 3",
    model: "Model Y",
    type: "Hatchback",
    fuel: "Diesel",
    color: "blue",
  },
  {
    manufacturer: "Audi",
    vehicle: "Mini Escalade",
    model: "PT Cruiser",
    type: "Passenger Van",
    fuel: "Gasoline",
    color: "pink",
  },
  {
    manufacturer: "Porsche",
    vehicle: "Cadillac Taurus",
    model: "Expedition",
    type: "Extended Cab Pickup",
    fuel: "Electric",
    color: "gold",
  },
  {
    manufacturer: "Volkswagen",
    vehicle: "Toyota Element",
    model: "Model X",
    type: "Coupe",
    fuel: "Electric",
    color: "grey",
  },
  {
    manufacturer: "BMW",
    vehicle: "Nissan XTS",
    model: "Jetta",
    type: "Hatchback",
    fuel: "Electric",
    color: "red",
  },
  {
    manufacturer: "Mercedes Benz",
    vehicle: "Jeep Model 3",
    model: "Altima",
    type: "Wagon",
    fuel: "Diesel",
    color: "indigo",
  },
  {
    manufacturer: "Mazda",
    vehicle: "Cadillac XC90",
    model: "Prius",
    type: "Sedan",
    fuel: "Hybrid",
    color: "ivory",
  },
  {
    manufacturer: "Honda",
    vehicle: "Smart Challenger",
    model: "Impala",
    type: "Hatchback",
    fuel: "Diesel",
    color: "purple",
  },
  {
    manufacturer: "Rolls Royce",
    vehicle: "Hyundai Countach",
    model: "Explorer",
    type: "Wagon",
    fuel: "Electric",
    color: "lime",
  },
  {
    manufacturer: "Mazda",
    vehicle: "Lamborghini Expedition",
    model: "Volt",
    type: "Cargo Van",
    fuel: "Electric",
    color: "white",
  },
  {
    manufacturer: "Chevrolet",
    vehicle: "Lamborghini Explorer",
    model: "Durango",
    type: "Coupe",
    fuel: "Electric",
    color: "gold",
  },
  {
    manufacturer: "Jeep",
    vehicle: "Land Rover Element",
    model: "El Camino",
    type: "Cargo Van",
    fuel: "Hybrid",
    color: "fuchsia",
  },
  {
    manufacturer: "Volvo",
    vehicle: "Volvo Mustang",
    model: "Fortwo",
    type: "SUV",
    fuel: "Gasoline",
    color: "plum",
  },
  {
    manufacturer: "Tesla",
    vehicle: "Aston Martin Durango",
    model: "Grand Cherokee",
    type: "Cargo Van",
    fuel: "Electric",
    color: "grey",
  },
  {
    manufacturer: "Audi",
    vehicle: "Tesla A4",
    model: "Volt",
    type: "Cargo Van",
    fuel: "Gasoline",
    color: "olive",
  },
  {
    manufacturer: "Nissan",
    vehicle: "Porsche Model Y",
    model: "Wrangler",
    type: "Sedan",
    fuel: "Hybrid",
    color: "cyan",
  },
  {
    manufacturer: "Mazda",
    vehicle: "Mazda Taurus",
    model: "Aventador",
    type: "Sedan",
    fuel: "Hybrid",
    color: "salmon",
  },
  {
    manufacturer: "Kia",
    vehicle: "Smart PT Cruiser",
    model: "Corvette",
    type: "Hatchback",
    fuel: "Gasoline",
    color: "mint green",
  },
  {
    manufacturer: "Honda",
    vehicle: "Mercedes Benz Aventador",
    model: "Challenger",
    type: "Convertible",
    fuel: "Gasoline",
    color: "lavender",
  },
  {
    manufacturer: "Nissan",
    vehicle: "Smart Malibu",
    model: "Model T",
    type: "Coupe",
    fuel: "Gasoline",
    color: "red",
  },
  {
    manufacturer: "Jeep",
    vehicle: "Mini Grand Cherokee",
    model: "Fiesta",
    type: "Sedan",
    fuel: "Electric",
    color: "lime",
  },
];

